### ISSUE TITLE
osx installer does not work

### ISSUE THREAD

**Issue by Qsilver97** [Qsilver97/Qwallet#50]

**Comment by RealWorld777** [comment]
i think osx installer must be built in macOS, not ubuntu.
here is code:
```
build-and-upload-linux:
    runs-on: ubuntu-latest // i think we have to change this.
    steps:
     .............................
```
